export interface ReasoningNode {
  id: string;
  type: "Concept" | "Relation" | "Rule" | "Conclusion";
  title: string;
  subtitle?: string;
  description?: string;
  icon?: "user" | "scale" | "book";
  badge?: string;
}

export interface ReasoningEdge {
  from: string;
  to: string;
  type: "Direct" | "Analogical" | "Derivation";
}

export interface NodeInspectorData {
  type: string;
  source: string;
  sourceInfo?: string;
  strength: number; // 1-5 star rating
  confidence: number; // 0-100 percentage
  whyFired: string;
  exceptions: string;
  relatedConflicts: string;
}

export interface ReasoningTree {
  statusBadge: string;
  confidenceVal: number;
  nodes: ReasoningNode[];
  edges: ReasoningEdge[];
  inspectorData: Record<string, NodeInspectorData>;
}

export interface AnswerData {
  id: string;
  question: string;
  category: string;
  summary: string;
  analysis: string;
  references: string[];
  notes: string;
  confidence: "High" | "Medium" | "Low";
  disclaimer: string;
  reasoningTree?: ReasoningTree;
}

/**
 * Structured mock juristic answers database representing Tarjih's analysis results.
 * Follows the visual response schema contract with full interactive reasoning trees.
 */
export const answersData: AnswerData[] = [
  {
    id: "mistreating-aunts",
    question: "Is mistreating aunts haram?",
    category: "General (Ethics)",
    summary: "Yes. By analogy (Qiyas) from the explicit prohibition against mistreating mothers, jurists extend the same strict requirement of respect, honor, and gentle treatment to maternal and paternal aunts.",
    analysis: "The ruling on mistreating aunts is established through the jurisprudential mechanism of Qiyas (analogy). The primary text (Asl) is the Quranic and Hadith consensus prohibiting the mistreatment or disrespect of mothers, which is defined as a major sin (Uquq).\n\nThe common effective cause (Illah) between a mother and an aunt is the binding ties of kinship (Rahim) and maternal lineage, as the maternal aunt occupies a status similar to the mother in care and respect. This is corroborated by the Hadith of the Prophet (peace be upon him): 'The maternal aunt is of the same status as the mother.'\n\nTherefore, the ruling (Hukm) of prohibition is extended from the mother to the aunt, rendering any form of mistreatment, severing of ties, or disrespect toward aunts as strictly forbidden (Haram) or highly prohibited.",
    references: [
      "Sahih al-Bukhari (Hadith 5975 regarding ties of kinship)",
      "Sahih Muslim (Hadith 2548 - 'The maternal aunt is of the same status as the mother')",
      "Al-Mabsut by al-Sarakhsi (Vol. 5, Chapter on Family Maintenance)",
      "Qawa'id al-Ahkam by al-Izz ibn Abd al-Salam"
    ],
    notes: "This ruling applies universally to both maternal and paternal aunts. While the mother's rights are supreme, the rights of aunts are strongly protected under the general obligation of maintaining kinship ties (Silat al-Rahim).",
    confidence: "High",
    disclaimer: "This response is generated by Tarjih for study and research purposes, and should not be considered an official fatwa.",
    reasoningTree: {
      statusBadge: "Likely Forbidden",
      confidenceVal: 87,
      nodes: [
        { id: "aunt", type: "Concept", title: "Aunt", subtitle: "(Maternal Relative)", badge: "Concept", icon: "user" },
        { id: "mother", type: "Concept", title: "Mother", subtitle: "(Direct Ascendant)", badge: "Concept", icon: "user" },
        { id: "qiyas", type: "Relation", title: "Qiyas (Analogy)", description: "Respect-duty extends from mother to maternal kin.", badge: "Relation", icon: "scale" },
        { id: "rule", type: "Rule", title: "Rule", description: "Mistreating mother is forbidden.", badge: "Rule", icon: "book" },
        { id: "conclusion", type: "Conclusion", title: "Conclusion", description: "Mistreating aunt is likely forbidden.", badge: "Conclusion", icon: "scale" }
      ],
      edges: [
        { from: "aunt", to: "qiyas", type: "Analogical" },
        { from: "mother", to: "qiyas", type: "Analogical" },
        { from: "qiyas", to: "conclusion", type: "Derivation" },
        { from: "rule", to: "conclusion", type: "Derivation" }
      ],
      inspectorData: {
        conclusion: {
          type: "Conclusion",
          source: "Derived (Qiyas)",
          sourceInfo: "Sahih Muslim",
          strength: 5,
          confidence: 87,
          whyFired: "By qiyas from the established rule that mistreating one's mother is forbidden, the same duty of respect is extended to maternal aunts.",
          exceptions: "No direct textual exception found.",
          relatedConflicts: "None"
        },
        aunt: {
          type: "Concept",
          source: "Legal Status (Maternal Kin)",
          strength: 5,
          confidence: 95,
          whyFired: "Identified as a secondary subject of kinship ties, sharing a maternal branch with the direct ascendant.",
          exceptions: "None",
          relatedConflicts: "None"
        },
        mother: {
          type: "Concept",
          source: "Textual (Direct Ascendant)",
          strength: 5,
          confidence: 100,
          whyFired: "Identified as the primary subject of absolute respect and filial piety under explicit Quranic commands.",
          exceptions: "None",
          relatedConflicts: "None"
        },
        qiyas: {
          type: "Relation",
          source: "Juristic Deduction",
          strength: 4,
          confidence: 85,
          whyFired: "Weighs the effective cause ('Illah) of maternal relationship, extending the obligation of honoring from mother to her sister.",
          exceptions: "Subject to difference between schools on scope of Rahim.",
          relatedConflicts: "None"
        },
        rule: {
          type: "Rule",
          source: "Quranic Text",
          strength: 5,
          confidence: 100,
          whyFired: "The explicit prohibition of 'Uquq (disobedience/mistreatment) of parents, specifically the mother, as a major sin.",
          exceptions: "None",
          relatedConflicts: "None"
        }
      }
    }
  },
  {
    id: "combining-prayers",
    question: "Is it permissible to combine prayers while traveling?",
    category: "Worship (Ibadah)",
    summary: "Yes, combining prayers (Jam') during travel is permissible and considered a valid concession (Rukhshah) across the majority of Islamic jurisprudence, provided the travel meets specific distance and intent criteria.",
    analysis: "Islamic scholars generally agree that traveling is a valid excuse to combine Dhuhr with Asr, and Maghrib with Isha, either by bringing the second prayer forward (Jam' Ta'dim) or delaying the first (Jam' Ta'khir). The primary evidence is derived from the Sunnah, where the Prophet Muhammad (peace be upon him) combined prayers during the expedition to Tabuk and during his farewell pilgrimage. The Hanafi school represents a notable exception, holding that prayers may only be combined during the Hajj pilgrimage at Arafah and Muzdalifah, and that otherwise, each prayer must be performed in its own time. The Shafi'i, Maliki, and Hanbali schools permit it for any travel that exceeds the standard distance threshold (roughly 80 kilometers or 48 miles) and is not undertaken for a sinful purpose.",
    references: [
      "Sahih al-Bukhari, Book of Shortening the Prayers (Hadith 1080)",
      "Sahih Muslim, Book of the Prayer of Travelers (Hadith 705)",
      "Al-Mughni by Ibn Qudamah (Vol. 2, Page 201)",
      "Fath al-Bari by Ibn Hajar al-Asqalani (Vol. 2, Page 579)"
    ],
    notes: "Scholars differ on whether combining is permissible for short journeys. Additionally, the concessions of travel (shortening and combining) terminate immediately once the traveler returns to their home city or intends to stay in a destination for more than four days (according to the majority).",
    confidence: "High",
    disclaimer: "This response is generated by Tarjih for study and research purposes, and should not be considered an official fatwa.",
    reasoningTree: {
      statusBadge: "Permissible Concession",
      confidenceVal: 95,
      nodes: [
        { id: "journey", type: "Concept", title: "Travel (>80km)", subtitle: "(Physical Journey)", badge: "Concept", icon: "user" },
        { id: "hardship", type: "Concept", title: "Hardship", subtitle: "(Juristic Cause)", badge: "Concept", icon: "user" },
        { id: "rukhshah", type: "Relation", title: "Rukhshah (Concession)", description: "Concession of travel is designed to remove hardship.", badge: "Relation", icon: "scale" },
        { id: "rule", type: "Rule", title: "General Rule", description: "Prayers must be performed in their fixed times.", badge: "Rule", icon: "book" },
        { id: "conclusion", type: "Conclusion", title: "Conclusion", description: "Combining prayers is permitted during travel.", badge: "Conclusion", icon: "scale" }
      ],
      edges: [
        { from: "journey", to: "rukhshah", type: "Analogical" },
        { from: "hardship", to: "rukhshah", type: "Analogical" },
        { from: "rukhshah", to: "conclusion", type: "Derivation" },
        { from: "rule", to: "conclusion", type: "Derivation" }
      ],
      inspectorData: {
        conclusion: {
          type: "Conclusion",
          source: "Sunnah & Consensus (Majority)",
          sourceInfo: "Sahih al-Bukhari & Muslim",
          strength: 5,
          confidence: 95,
          whyFired: "The Prophet (pbuh) combined prayers during several journeys, establishing a clear concession (Rukhshah) to alleviate difficulty for the Ummah.",
          exceptions: "Hanafi school restricts combining strictly to Hajj at Arafah and Muzdalifah.",
          relatedConflicts: "Hanafi textual interpretation (apparent combining vs. real combining)"
        },
        journey: {
          type: "Concept",
          source: "Textual Consensus",
          strength: 5,
          confidence: 98,
          whyFired: "The traveler must exceed the minimum distance threshold (80km) to qualify for travel concessions.",
          exceptions: "Local customs (Urf) may redefine what constitutes travel in modern transit.",
          relatedConflicts: "Varying distance definitions among traditional schools."
        },
        hardship: {
          type: "Concept",
          source: "Juristic Principle",
          strength: 5,
          confidence: 90,
          whyFired: "Based on the foundational legal maxim: 'Hardship brings about facility' (Al-Mashaqqatu Tajlibu al-Taysir).",
          exceptions: "Concession remains valid even if no actual physical hardship is felt during modern comfortable travel.",
          relatedConflicts: "None"
        },
        rukhshah: {
          type: "Relation",
          source: "Deduction from Sunnah",
          strength: 5,
          confidence: 95,
          whyFired: "Integrates travel and hardship to trigger the divine license (Rukhshah) rather than the standard strict rule.",
          exceptions: "Travel for sinful purposes (Safar al-Ma'siyah) invalidates the right to use concessions in some schools.",
          relatedConflicts: "None"
        },
        rule: {
          type: "Rule",
          source: "Quranic Text",
          strength: 5,
          confidence: 100,
          whyFired: "The standard default obligation: 'Indeed, prayer has been decreed upon the believers a decree of specified times' (Quran 4:103).",
          exceptions: "Fasting, travel, sickness, rain, and fear are standard causes for deviation from the default rule.",
          relatedConflicts: "None"
        }
      }
    }
  },
  {
    id: "cryptocurrency",
    question: "What is the juristic ruling on transactions using digital currencies (Cryptocurrencies)?",
    category: "Transactions (Muamalat)",
    summary: "The contemporary ruling on cryptocurrency is highly debated. Some scholars permit it as a digital asset subject to normal exchange rules, while others prohibit it due to excessive uncertainty (Gharar), lack of central authority regulation, and speculation (Qimar).",
    analysis: "Contemporary jurists are divided into three main opinions. The first group (including several national fatwa councils) prohibits cryptocurrency, arguing that it lacks the qualities of legal tender (Maliyyah/Thamaniyyah) recognized by a sovereign authority, leads to high volatility and speculation, and can facilitate illegal transactions. The second group permits it, viewing it as a digital asset (Mal) that holds utility and is voluntarily accepted by transacting parties as a medium of exchange. They argue that cryptocurrency functions similarly to custom fiat currency (Fulus) in traditional jurisprudence. The third group remains neutral, waiting for further regulatory maturation. The core debate centers on whether volatility constitutes prohibited Gharar (uncertainty) or standard market risk, and whether government backing is an absolute prerequisite for currency.",
    references: [
      "International Islamic Fiqh Academy (IIFA) Resolution on Digital Currencies",
      "Fatwa of the Turkish Directorate of Religious Affairs (Diyanet)",
      "Research Papers of the Accounting and Auditing Organization for Islamic Financial Institutions (AAOIFI)",
      "Islamic Finance and Cryptocurrencies by various contemporary scholars"
    ],
    notes: "Rulings may differ depending on the specific cryptocurrency design. Stablecoins backed by physical assets or fiat currency generally face fewer objections regarding volatility (Gharar) than highly speculative utility or meme tokens.",
    confidence: "Medium",
    disclaimer: "This response is generated by Tarjih for study and research purposes, and should not be considered an official fatwa.",
    reasoningTree: {
      statusBadge: "Highly Disputed / Restricted",
      confidenceVal: 60,
      nodes: [
        { id: "crypto", type: "Concept", title: "Cryptocurrency", subtitle: "(Digital Asset)", badge: "Concept", icon: "user" },
        { id: "volatility", type: "Concept", title: "Volatility & Speculation", subtitle: "(Market Reality)", badge: "Concept", icon: "user" },
        { id: "sad-dhara", type: "Relation", title: "Sadd al-Dhara'i", description: "Blocking the means to systemic wealth loss or deception.", badge: "Relation", icon: "scale" },
        { id: "rule", type: "Rule", title: "General Rule", description: "All contracts must be free of Gharar (uncertainty) and Qimar.", badge: "Rule", icon: "book" },
        { id: "conclusion", type: "Conclusion", title: "Conclusion", description: "Trading is highly restricted or prohibited.", badge: "Conclusion", icon: "scale" }
      ],
      edges: [
        { from: "crypto", to: "sad-dhara", type: "Analogical" },
        { from: "volatility", to: "sad-dhara", type: "Analogical" },
        { from: "sad-dhara", to: "conclusion", type: "Derivation" },
        { from: "rule", to: "conclusion", type: "Derivation" }
      ],
      inspectorData: {
        conclusion: {
          type: "Conclusion",
          source: "Juristic Discretion (Ijtihad)",
          sourceInfo: "Global Fatwa Councils",
          strength: 3,
          confidence: 60,
          whyFired: "Multiple contemporary councils rule prohibition due to excessive Gharar, high speculation (resembling gambling), and lack of state regulatory authority.",
          exceptions: "Permissible as a utility asset if backed by tangible underlying value or stable assets.",
          relatedConflicts: "Concessions for digital assets vs. strict definition of legal tender (Thamaniyyah)."
        },
        crypto: {
          type: "Concept",
          source: "Financial Analysis",
          strength: 4,
          confidence: 80,
          whyFired: "Analyzed as a decentralized token. Lacks intrinsic value or sovereign backing, functioning purely on algorithmic and network consensus.",
          exceptions: "Central Bank Digital Currencies (CBDCs) escape this classification.",
          relatedConflicts: "Is sovereign backing (Sultan) required for currency, or is societal custom (Urf) sufficient?"
        },
        volatility: {
          type: "Concept",
          source: "Empirical Observation",
          strength: 5,
          confidence: 95,
          whyFired: "Extreme price fluctuations driven by speculative trading rather than fundamental economic utility.",
          exceptions: "Asset-backed stablecoins exhibit minimal volatility.",
          relatedConflicts: "None"
        },
        "sad-dhara": {
          type: "Relation",
          source: "Legal Maxim",
          strength: 4,
          confidence: 70,
          whyFired: "Invokes Sadd al-Dhara'i (blocking the means to harm) to protect retail investors from massive financial loss and prevent black market usage.",
          exceptions: "If regulatory frameworks emerge to protect consumers, the application of this blocking rule may adapt.",
          relatedConflicts: "None"
        },
        rule: {
          type: "Rule",
          source: "Textual Consensus",
          strength: 5,
          confidence: 100,
          whyFired: "The strict prohibition of Gharar (uncertainty) in contracts as stated by the Prophet (pbuh) in Sahih Muslim, and the general Quranic prohibition of consuming wealth unjustly.",
          exceptions: "Slight uncertainty (Gharar Yasir) is overlooked if necessary for public convenience.",
          relatedConflicts: "None"
        }
      }
    }
  },
  {
    id: "stocks-zakat",
    question: "How is the modern Zakat calculated on investments and corporate stocks?",
    category: "Financials (Zakat)",
    summary: "Zakat on stocks depends on the investor's intent. Long-term investors (focused on dividends) pay Zakat on their share of the company's zakat-eligible assets (or a flat 10% of net dividends), whereas short-term traders pay 2.5% on the full market value of their portfolio.",
    analysis: "According to the International Islamic Fiqh Academy and AAOIFI standards, stock investments are treated in two ways. (1) For Long-term Investors (Acquisition/Investment): If the corporation itself pays Zakat on behalf of shareholders, the individual is exempted. If not, the investor must determine the company's zakatable assets (Current Assets minus Current Liabilities) and pay 2.5% on their proportional share. Alternatively, several modern jurists permit paying a simplified 10% on the received dividends. (2) For Short-term Traders (Speculators/Trade): The stocks are treated as trading goods ('Urud al-Tijarah). The investor must evaluate the entire portfolio at market value on their Zakat anniversary date, add cash balances, and pay 2.5% on the total sum, provided it meets the Nisab threshold.",
    references: [
      "IIFA Resolution No. 28 (3/4) regarding Zakat on Shares",
      "AAOIFI Shariah Standard No. 35 (Zakat)",
      "Fatawa of the Zakat House of Kuwait",
      "Fiqh al-Zakat by Dr. Yusuf al-Qaradawi"
    ],
    notes: "Zakat is only payable on shares of companies engaged in Shariah-compliant business activities. If a company has mixed income, purification (paying out the non-compliant income portion to charity) must be completed before calculating Zakat.",
    confidence: "High",
    disclaimer: "This response is generated by Tarjih for study and research purposes, and should not be considered an official fatwa.",
    reasoningTree: {
      statusBadge: "Intention-Based Dual Rule",
      confidenceVal: 90,
      nodes: [
        { id: "speculator", type: "Concept", title: "Short-term Trader", subtitle: "(Trading Intent)", badge: "Concept", icon: "user" },
        { id: "investor", type: "Concept", title: "Long-term Holder", subtitle: "(Dividend Intent)", badge: "Concept", icon: "user" },
        { id: "urud-tijarah", type: "Relation", title: "Urud al-Tijarah", description: "Trading goods rules apply to active stock portfolios.", badge: "Relation", icon: "scale" },
        { id: "rule", type: "Rule", title: "General Rule", description: "Zakat is due at 2.5% on growing wealth (Mal Nami).", badge: "Rule", icon: "book" },
        { id: "conclusion", type: "Conclusion", title: "Conclusion", description: "Pay 2.5% on full value (trader) or 10% on dividends (holder).", badge: "Conclusion", icon: "scale" }
      ],
      edges: [
        { from: "speculator", to: "urud-tijarah", type: "Analogical" },
        { from: "investor", to: "urud-tijarah", type: "Analogical" },
        { from: "urud-tijarah", to: "conclusion", type: "Derivation" },
        { from: "rule", to: "conclusion", type: "Derivation" }
      ],
      inspectorData: {
        conclusion: {
          type: "Conclusion",
          source: "Juristic Consensus (IIFA / AAOIFI)",
          sourceInfo: "AAOIFI Standard 35",
          strength: 5,
          confidence: 90,
          whyFired: "Aligns with classical rules of trading goods for active traders, and partnership shares (company assets) for long-term investors.",
          exceptions: "If the company itself calculates and pays Zakat on behalf of all shareholders, no individual Zakat is due.",
          relatedConflicts: "Simplified flat 10% dividend calculation vs. exact balance sheet analysis."
        },
        speculator: {
          type: "Concept",
          source: "Juristic Definition",
          strength: 5,
          confidence: 95,
          whyFired: "Defined as an actor purchasing stocks with the primary intent of reselling them for short-term capital gains, treating shares as merchandise.",
          exceptions: "None",
          relatedConflicts: "None"
        },
        investor: {
          type: "Concept",
          source: "Juristic Definition",
          strength: 5,
          confidence: 95,
          whyFired: "Defined as an actor holding stocks to secure long-term dividends, acting as a fractional partner in the company's real assets.",
          exceptions: "None",
          relatedConflicts: "None"
        },
        "urud-tijarah": {
          type: "Relation",
          source: "Analogy to Trade Goods",
          strength: 5,
          confidence: 92,
          whyFired: "Weighs intent and categorizes trading stock as merchandise, triggering immediate valuation at current market prices.",
          exceptions: "Fixed assets of the company are excluded from the zakat base for long-term investors.",
          relatedConflicts: "None"
        },
        rule: {
          type: "Rule",
          source: "Textual Consensus & Maxims",
          strength: 5,
          confidence: 100,
          whyFired: "Foundational rules of Zakat demanding 2.5% on qualifying surplus wealth that has met Nisab and completed a lunar year (Hawl).",
          exceptions: "Agricultural wealth (Ushr) and gold/silver have slightly different thresholds or rates.",
          relatedConflicts: "None"
        }
      }
    }
  }
];
